# Generated by Django 4.2.6 on 2023-10-30 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_new_bid_comment_comment_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='wished_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Item', to='auctions.listing'),
        ),
    ]
