# Generated by Django 4.2.6 on 2023-10-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_owner_wishlist_user_wishlist_wished_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(to='auctions.listing'),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
