# Generated by Django 4.2.6 on 2023-11-08 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_active_alter_listing_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bidder',
        ),
        migrations.AlterField(
            model_name='listing',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(related_name='users_wishlist', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bidder',
            field=models.ManyToManyField(blank=True, related_name='bidder_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
